// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupInfo describes one backup file for the restore dialog.
 */
export interface BackupInfo {
    "path": string;
    "time": string;
    "categories": number;
    "entries": number;
}

/**
 * Category groups entries. The order of categories inside Data.Categories is
 * the display order (per kind).
 */
export interface Category {
    "id": string;
    "name": string;
    "kind": Kind;

    /**
     * Collapsed remembers whether the category is folded in the main view.
     */
    "collapsed": boolean;
}

/**
 * CategoryView is a category with its entries and subtotals. Paused entries
 * are listed but do not count towards the subtotals.
 */
export interface CategoryView {
    "id": string;
    "name": string;
    "kind": Kind;

    /**
     * Collapsed remembers whether the category is folded in the main view.
     */
    "collapsed": boolean;
    "entries": EntryView[] | null;
    "monthlyCents": number;
    "yearlyCents": number;
}

/**
 * Entry is a single income or spending. The order of entries inside
 * Data.Entries is the display order within a category.
 */
export interface Entry {
    "id": string;
    "categoryId": string;
    "name": string;

    /**
     * AmountCents is the amount the user entered, in cents, for the Period.
     */
    "amountCents": number;
    "period": Period;

    /**
     * DueMonth is the calendar month (1-12) of a payment for non-monthly
     * entries, 0 if not set. Quarterly and half-yearly entries pay every
     * 3 or 6 months starting from that month.
     */
    "dueMonth"?: number;

    /**
     * Paused entries are kept but excluded from all totals and statistics.
     */
    "paused"?: boolean;

    /**
     * Notes is free text, e.g. a contract number or cancellation date.
     */
    "notes"?: string;
}

/**
 * EntryInput holds the editable fields of an entry as entered in the dialog.
 */
export interface EntryInput {
    "categoryId": string;
    "name": string;
    "amountCents": number;
    "period": Period;
    "dueMonth": number;
    "paused": boolean;
    "notes": string;
}

/**
 * EntryView is an entry enriched with the derived values shown in the table.
 */
export interface EntryView {
    "id": string;
    "categoryId": string;
    "name": string;

    /**
     * AmountCents is the amount the user entered, in cents, for the Period.
     */
    "amountCents": number;
    "period": Period;

    /**
     * DueMonth is the calendar month (1-12) of a payment for non-monthly
     * entries, 0 if not set. Quarterly and half-yearly entries pay every
     * 3 or 6 months starting from that month.
     */
    "dueMonth"?: number;

    /**
     * Paused entries are kept but excluded from all totals and statistics.
     */
    "paused"?: boolean;

    /**
     * Notes is free text, e.g. a contract number or cancellation date.
     */
    "notes"?: string;
    "monthlyCents": number;
    "yearlyCents": number;
}

/**
 * ImportMode tells ImportData what to do with the current data.
 */
export enum ImportMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ImportReplace throws the current data away and uses the imported data.
     */
    ImportReplace = "replace",

    /**
     * ImportMerge adds the imported categories and entries to the current
     * data. Categories with the same name and kind are reused.
     */
    ImportMerge = "merge",
};

/**
 * ImportPreview describes a file selected for import, so that the UI can ask
 * the user whether to merge or replace before anything is changed.
 */
export interface ImportPreview {
    /**
     * Path is empty if the user cancelled the file dialog.
     */
    "path": string;
    "version": number;
    "categories": number;
    "entries": number;
}

/**
 * ImportResult is returned by ImportData: the new state plus a report of
 * what the import did, shown to the user in a notification.
 */
export interface ImportResult {
    "state": State;
    "categoriesAdded": number;
    "categoriesReused": number;
    "entriesAdded": number;
    "entriesSkipped": number;

    /**
     * BackupPath is the backup written right before the import; restoring
     * it undoes the import.
     */
    "backupPath": string;
}

/**
 * Kind distinguishes income from spending. Categories belong to exactly one
 * kind, entries inherit the kind of their category.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindIncome = "income",
    KindSpending = "spending",
};

/**
 * Period is the "master" period of an entry: the period the user entered the
 * amount for. The other values are derived (see calc.go).
 */
export enum Period {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PeriodMonthly = "monthly",
    PeriodQuarterly = "quarterly",
    PeriodHalfYearly = "halfyearly",
    PeriodYearly = "yearly",
};

/**
 * SampleResult reports what LoadSampleData created.
 */
export interface SampleResult {
    "state": State;
    "categories": number;
    "entries": number;
}

/**
 * Settings holds user preferences that are stored together with the data.
 */
export interface Settings {
    /**
     * Language is the UI language code chosen by the user, e.g. "en" or
     * "de". It stays empty until a choice was made; the frontend then uses
     * its default language (German).
     */
    "language": string;

    /**
     * SavingsGoalCents is the amount the user wants to put aside per month.
     */
    "savingsGoalCents": number;

    /**
     * Window is the last window geometry (zero = use the default size).
     */
    "window": WindowGeometry;
}

/**
 * State is everything the frontend needs to render the main view.
 */
export interface State {
    "version": number;
    "dataPath": string;
    "settings": Settings;
    "income": CategoryView[] | null;
    "spending": CategoryView[] | null;
    "stats": Stats;
}

/**
 * Stats is the content of the statistics box.
 * 
 * The background: monthly spendings are paid from the bank account, so that
 * amount has to be transferred to the bank account every month. Quarterly,
 * half-yearly and yearly spendings are saved up on a savings account with
 * 1/n of the amount every month, so that the money is available when the
 * spending is due.
 */
export interface Stats {
    "incomeMonthlyCents": number;
    "incomeYearlyCents": number;

    /**
     * average cost per month
     */
    "spendingMonthlyCents": number;
    "spendingYearlyCents": number;
    "saldoMonthlyCents": number;
    "saldoYearlyCents": number;

    /**
     * ToBankMonthlyCents is the sum of all spendings entered per month.
     */
    "toBankMonthlyCents": number;

    /**
     * ToSavingsMonthlyCents is the monthly share of all spendings that are
     * not paid monthly.
     */
    "toSavingsMonthlyCents": number;

    /**
     * SavingsGoalCents is the amount the user wants to put aside per month.
     */
    "savingsGoalCents": number;

    /**
     * RemainingAfterGoalCents is the monthly saldo minus the savings goal.
     */
    "remainingAfterGoalCents": number;
    "goalReachable": boolean;

    /**
     * Timeline shows, per calendar month, what is due and how much the
     * savings account holds. Only entries with a due month take part.
     */
    "timeline": TimelineMonth[];

    /**
     * PeakBufferCents is the highest savings balance of the year, i.e. the
     * buffer the savings account needs.
     */
    "peakBufferCents": number;

    /**
     * UnscheduledCount is the number of active non-monthly spendings without
     * a due month (not part of the timeline).
     */
    "unscheduledCount": number;

    /**
     * PausedCount is the number of paused entries (income and spending).
     */
    "pausedCount": number;
}

/**
 * TimelineMonth describes one calendar month (index 0 = January) of the
 * steady-state savings plan.
 */
export interface TimelineMonth {
    /**
     * DueCents is the sum of non-monthly spendings that are paid in this month.
     */
    "dueCents": number;

    /**
     * SavedCents is the balance the savings account holds at the end of the
     * month, after the month's contribution and payments.
     */
    "savedCents": number;
}

/**
 * WindowGeometry remembers the window size and position between starts.
 */
export interface WindowGeometry {
    "width": number;
    "height": number;
    "x": number;
    "y": number;
}
