// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CategoryView is a category with its entries and subtotals.
 */
export interface CategoryView {
    "id": string;
    "name": string;
    "kind": Kind;

    /**
     * Collapsed remembers whether the category is folded in the main view.
     */
    "collapsed": boolean;
    "entries": EntryView[] | null;
    "monthlyCents": number;
    "yearlyCents": number;
}

/**
 * EntryView is an entry enriched with the derived values shown in the table.
 */
export interface EntryView {
    "id": string;
    "categoryId": string;
    "name": string;

    /**
     * AmountCents is the amount the user entered, in cents, for the Period.
     */
    "amountCents": number;
    "period": Period;
    "monthlyCents": number;
    "yearlyCents": number;
}

/**
 * ImportMode tells ImportData what to do with the current data.
 */
export enum ImportMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ImportReplace throws the current data away and uses the imported data.
     */
    ImportReplace = "replace",

    /**
     * ImportMerge adds the imported categories and entries to the current
     * data. Categories with the same name and kind are reused.
     */
    ImportMerge = "merge",
};

/**
 * ImportPreview describes a file selected for import, so that the UI can ask
 * the user whether to merge or replace before anything is changed.
 */
export interface ImportPreview {
    /**
     * Path is empty if the user cancelled the file dialog.
     */
    "path": string;
    "version": number;
    "categories": number;
    "entries": number;
}

/**
 * ImportResult is returned by ImportData: the new state plus a report of
 * what the import did, shown to the user in a notification.
 */
export interface ImportResult {
    "state": State;
    "categoriesAdded": number;
    "categoriesReused": number;
    "entriesAdded": number;
    "entriesSkipped": number;
}

/**
 * Kind distinguishes income from spending. Categories belong to exactly one
 * kind, entries inherit the kind of their category.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindIncome = "income",
    KindSpending = "spending",
};

/**
 * Period is the "master" period of an entry: the period the user entered the
 * amount for. The other period is derived (see calc.go).
 */
export enum Period {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PeriodMonthly = "monthly",
    PeriodYearly = "yearly",
};

/**
 * Settings holds user preferences that are stored together with the data.
 */
export interface Settings {
    /**
     * Language is the UI language code chosen by the user, e.g. "en" or
     * "de". It stays empty until a choice was made; the frontend then uses
     * its default language (German).
     */
    "language": string;
}

/**
 * State is everything the frontend needs to render the main view.
 */
export interface State {
    "version": number;
    "dataPath": string;
    "settings": Settings;
    "income": CategoryView[] | null;
    "spending": CategoryView[] | null;
    "stats": Stats;
}

/**
 * Stats is the content of the statistics box.
 * 
 * The background: monthly spendings are paid from the bank account, so that
 * amount has to be transferred to the bank account every month. Yearly
 * spendings are saved up on a savings account with 1/12 of the amount every
 * month, so that the money is available when the spending is due.
 */
export interface Stats {
    "incomeMonthlyCents": number;
    "incomeYearlyCents": number;

    /**
     * average cost per month
     */
    "spendingMonthlyCents": number;
    "spendingYearlyCents": number;
    "saldoMonthlyCents": number;
    "saldoYearlyCents": number;

    /**
     * ToBankMonthlyCents is the sum of all spendings entered per month.
     */
    "toBankMonthlyCents": number;

    /**
     * ToSavingsMonthlyCents is the sum of 1/12 of all spendings entered per year.
     */
    "toSavingsMonthlyCents": number;
}
