// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service used by the frontend. Every mutating method
 * persists the data immediately and returns the new State, so the frontend
 * simply replaces its state with the result.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCategory appends a new category of the given kind.
 */
export function AddCategory(kind: $models.Kind, name: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1052201935, kind, name);
}

/**
 * AddEntry appends a new entry to a category.
 */
export function AddEntry($in: $models.EntryInput): $CancellablePromise<$models.State> {
    return $Call.ByID(532656629, $in);
}

/**
 * ChooseImportFile asks the user for a file and returns a preview of its
 * content. The preview's Path is "" if the user cancelled.
 */
export function ChooseImportFile(): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(1686174830);
}

/**
 * DeleteCategory removes a category. It fails if any entry still uses it.
 */
export function DeleteCategory(id: string): $CancellablePromise<$models.State> {
    return $Call.ByID(2800549479, id);
}

/**
 * DeleteEntry removes an entry.
 */
export function DeleteEntry(id: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1471171869, id);
}

/**
 * ExportCSV asks the user for a target file and writes the CSV to it.
 * It returns the chosen path, or "" if the user cancelled.
 */
export function ExportCSV(): $CancellablePromise<string> {
    return $Call.ByID(3958737246);
}

/**
 * ExportCSVTo writes all entries as CSV to the given path.
 */
export function ExportCSVTo(path: string): $CancellablePromise<void> {
    return $Call.ByID(1813518083, path);
}

/**
 * ExportData asks the user for a target file and writes the data to it.
 * It returns the chosen path, or "" if the user cancelled.
 */
export function ExportData(): $CancellablePromise<string> {
    return $Call.ByID(1763547262);
}

/**
 * ExportTo writes the current data to the given path.
 */
export function ExportTo(path: string): $CancellablePromise<void> {
    return $Call.ByID(1967134563, path);
}

/**
 * GetState returns the current state for rendering.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2898915481);
}

/**
 * ImportData imports a file, either replacing the current data or merging
 * it into the current data (see Merge for the rules).
 */
export function ImportData(path: string, mode: $models.ImportMode): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3233648325, path, mode);
}

/**
 * ListBackups returns the available backups, newest first.
 */
export function ListBackups(): $CancellablePromise<$models.BackupInfo[] | null> {
    return $Call.ByID(3842607239);
}

/**
 * LoadSampleData fills an empty planner with example data in the given
 * language. It refuses to run when there already are categories or entries.
 */
export function LoadSampleData(lang: string): $CancellablePromise<$models.SampleResult> {
    return $Call.ByID(1503351070, lang);
}

/**
 * MoveCategory moves a category to position toIndex among the categories of
 * its own kind (0 = first).
 */
export function MoveCategory(id: string, toIndex: number): $CancellablePromise<$models.State> {
    return $Call.ByID(184336081, id, toIndex);
}

/**
 * MoveEntry moves an entry to position toIndex (0 = first) inside the target
 * category, which may be the entry's current category (reorder) or another
 * category of the same kind (re-categorise).
 */
export function MoveEntry(id: string, targetCategoryID: string, toIndex: number): $CancellablePromise<$models.State> {
    return $Call.ByID(3429705075, id, targetCategoryID, toIndex);
}

/**
 * PreviewImport reads a file and reports what it contains without changing
 * anything.
 */
export function PreviewImport(path: string): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(4137540337, path);
}

/**
 * RenameCategory changes the name of a category.
 */
export function RenameCategory(id: string, name: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1235635826, id, name);
}

/**
 * RestoreBackup replaces the current data with a backup. The current data
 * is backed up first, so a restore can be undone as well.
 */
export function RestoreBackup(path: string): $CancellablePromise<$models.State> {
    return $Call.ByID(787788460, path);
}

/**
 * RestoreCategory re-inserts a deleted (empty) category with its original
 * id at the given position among the categories of its kind.
 */
export function RestoreCategory(category: $models.Category, index: number): $CancellablePromise<$models.State> {
    return $Call.ByID(2738738770, category, index);
}

/**
 * RestoreEntry re-inserts a deleted entry with its original id at the given
 * position of its category ("undo" of DeleteEntry).
 */
export function RestoreEntry(entry: $models.Entry, index: number): $CancellablePromise<$models.State> {
    return $Call.ByID(393946482, entry, index);
}

/**
 * SetAllCollapsed folds or unfolds all categories of one kind ("expand all"
 * / "collapse all" at the top of the income and the spending block).
 */
export function SetAllCollapsed(kind: $models.Kind, collapsed: boolean): $CancellablePromise<$models.State> {
    return $Call.ByID(2246108268, kind, collapsed);
}

/**
 * SetCategoryCollapsed folds or unfolds one category.
 */
export function SetCategoryCollapsed(id: string, collapsed: boolean): $CancellablePromise<$models.State> {
    return $Call.ByID(1889659817, id, collapsed);
}

/**
 * SetEntryPaused excludes an entry from (or includes it again in) all totals.
 */
export function SetEntryPaused(id: string, paused: boolean): $CancellablePromise<$models.State> {
    return $Call.ByID(431773078, id, paused);
}

/**
 * SetLanguage stores the UI language chosen in the language dropdown.
 */
export function SetLanguage(language: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1410414146, language);
}

/**
 * SetSavingsGoal stores the monthly savings goal.
 */
export function SetSavingsGoal(cents: number): $CancellablePromise<$models.State> {
    return $Call.ByID(541102472, cents);
}

/**
 * SetTheme stores the chosen color scheme ("light", "dark" or "system").
 */
export function SetTheme(theme: string): $CancellablePromise<$models.State> {
    return $Call.ByID(2148831501, theme);
}

/**
 * SetWindow remembers the window geometry. It is called often while the
 * window is resized, so nothing is written when the geometry is unchanged.
 */
export function SetWindow(w: $models.WindowGeometry): $CancellablePromise<void> {
    return $Call.ByID(441641220, w);
}

/**
 * UpdateEntry changes all editable fields of an entry. When the category
 * changes, the entry is appended at the end of the new category.
 */
export function UpdateEntry(id: string, $in: $models.EntryInput): $CancellablePromise<$models.State> {
    return $Call.ByID(3853723511, id, $in);
}
