// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service used by the frontend. Every mutating method
 * persists the data immediately and returns the new State, so the frontend
 * simply replaces its state with the result.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCategory appends a new category of the given kind.
 */
export function AddCategory(kind: $models.Kind, name: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1052201935, kind, name);
}

/**
 * AddEntry appends a new entry to a category.
 */
export function AddEntry(categoryID: string, name: string, amountCents: number, period: $models.Period): $CancellablePromise<$models.State> {
    return $Call.ByID(532656629, categoryID, name, amountCents, period);
}

/**
 * ChooseImportFile asks the user for a file and returns a preview of its
 * content. The preview's Path is "" if the user cancelled.
 */
export function ChooseImportFile(): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(1686174830);
}

/**
 * DeleteCategory removes a category. It fails if any entry still uses it.
 */
export function DeleteCategory(id: string): $CancellablePromise<$models.State> {
    return $Call.ByID(2800549479, id);
}

/**
 * DeleteEntry removes an entry.
 */
export function DeleteEntry(id: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1471171869, id);
}

/**
 * ExportData asks the user for a target file and writes the data to it.
 * It returns the chosen path, or "" if the user cancelled.
 */
export function ExportData(): $CancellablePromise<string> {
    return $Call.ByID(1763547262);
}

/**
 * ExportTo writes the current data to the given path.
 */
export function ExportTo(path: string): $CancellablePromise<void> {
    return $Call.ByID(1967134563, path);
}

/**
 * GetState returns the current state for rendering.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2898915481);
}

/**
 * ImportData imports a file, either replacing the current data or merging
 * it into the current data (see Merge for the rules).
 */
export function ImportData(path: string, mode: $models.ImportMode): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3233648325, path, mode);
}

/**
 * MoveCategory moves a category to position toIndex among the categories of
 * its own kind (0 = first).
 */
export function MoveCategory(id: string, toIndex: number): $CancellablePromise<$models.State> {
    return $Call.ByID(184336081, id, toIndex);
}

/**
 * MoveEntry moves an entry to position toIndex (0 = first) inside the target
 * category, which may be the entry's current category (reorder) or another
 * category of the same kind (re-categorise).
 */
export function MoveEntry(id: string, targetCategoryID: string, toIndex: number): $CancellablePromise<$models.State> {
    return $Call.ByID(3429705075, id, targetCategoryID, toIndex);
}

/**
 * PreviewImport reads a file and reports what it contains without changing
 * anything.
 */
export function PreviewImport(path: string): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(4137540337, path);
}

/**
 * RenameCategory changes the name of a category.
 */
export function RenameCategory(id: string, name: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1235635826, id, name);
}

/**
 * SetAllCollapsed folds or unfolds all categories of one kind ("expand all"
 * / "collapse all" at the top of the income and the spending block).
 */
export function SetAllCollapsed(kind: $models.Kind, collapsed: boolean): $CancellablePromise<$models.State> {
    return $Call.ByID(2246108268, kind, collapsed);
}

/**
 * SetCategoryCollapsed folds or unfolds one category.
 */
export function SetCategoryCollapsed(id: string, collapsed: boolean): $CancellablePromise<$models.State> {
    return $Call.ByID(1889659817, id, collapsed);
}

/**
 * SetLanguage stores the UI language chosen in the language dropdown.
 */
export function SetLanguage(language: string): $CancellablePromise<$models.State> {
    return $Call.ByID(1410414146, language);
}

/**
 * UpdateEntry changes all editable fields of an entry. When the category
 * changes, the entry is appended at the end of the new category.
 */
export function UpdateEntry(id: string, categoryID: string, name: string, amountCents: number, period: $models.Period): $CancellablePromise<$models.State> {
    return $Call.ByID(3853723511, id, categoryID, name, amountCents, period);
}
