import type { Messages } from "./index.ts";

/** German messages. See en.ts for the meaning of the keys. */
export const de: Messages = {
  "app.title": "Finanzplaner",
  "app.language": "Sprache",
  "app.theme": "Darstellung",
  "theme.light": "Hell",
  "theme.dark": "Dunkel",
  "theme.system": "System",
  "app.loading": "Lädt…",
  "app.loadError": "Die Datendatei konnte nicht geladen werden.",
  "app.retry": "Erneut versuchen",
  "app.import": "Importieren",
  "app.export": "Exportieren",
  "app.exportCsv": "CSV exportieren",
  "app.backups": "Backups",
  "app.print": "Drucken",
  "app.selectMode": "Einträge auswählen",
  "print.generated": "Gedruckt am {date}",
  "app.shortcuts": "Tastenkürzel",
  "app.search": "Einträge suchen…",
  "app.searchClear": "Suche löschen",
  "app.filterReset": "Suche und Filter zurücksetzen",
  "app.filter.all": "Alle Zeiträume",
  "app.filter.paused": "Nur pausierte",
  "app.filterResult": "{shown} von {total} Einträgen angezeigt",
  "app.getStarted.title": "Dein Planer ist leer.",
  "app.getStarted.text": "Lege Kategorien und Einträge an, importiere eine Datei oder lade ein kleines Beispiel, um zu sehen, wie der Planer funktioniert.",
  "app.getStarted.sample": "Beispieldaten laden",
  "confirm.sample.title": "Beispieldaten laden",
  "confirm.sample.message": "Ein Beispiel mit Kategorien und Einträgen laden? Alles kann danach bearbeitet oder gelöscht werden.",
  "confirm.sample.confirm": "Laden",
  "toast.sampleLoaded": "{categories} und {entries} geladen.",
  "toast.exportedCsv": "CSV exportiert nach {path}",
  "toast.undo": "Rückgängig",
  "toast.undoImport": "Import rückgängig",
  "toast.restored": "Wiederhergestellt.",
  "toast.backupRestored": "Backup wiederhergestellt.",
  "backups.title": "Backups",
  "backups.intro": "Backups werden automatisch vor Änderungen (höchstens alle 10 Minuten) und vor jedem Import angelegt. Die letzten 20 bleiben im Ordner backups neben data.json erhalten.",
  "backups.empty": "Noch keine Backups.",
  "backups.restore": "Wiederherstellen",
  "backups.content": "{categories}, {entries}",
  "confirm.restoreBackup.title": "Backup wiederherstellen",
  "confirm.restoreBackup.message": "Die aktuellen Daten durch das Backup vom {time} ersetzen? Die aktuellen Daten werden vorher gesichert.",
  "confirm.restoreBackup.confirm": "Wiederherstellen",
  "palette.placeholder": "Befehl, Kategorie oder Eintrag eingeben…",
  "palette.actions": "Aktionen",
  "palette.categories": "Kategorien",
  "palette.entries": "Einträge",
  "palette.empty": "Nichts gefunden.",
  "palette.hint": "↑↓ bewegen · Enter ausführen · Esc schließen",
  "palette.expandIncome": "Alle Einnahmen-Kategorien aufklappen",
  "palette.collapseIncome": "Alle Einnahmen-Kategorien zuklappen",
  "palette.expandSpending": "Alle Ausgaben-Kategorien aufklappen",
  "palette.collapseSpending": "Alle Ausgaben-Kategorien zuklappen",
  "palette.newIncomeCategory": "Neue Einnahmen-Kategorie",
  "palette.newSpendingCategory": "Neue Ausgaben-Kategorie",
  "palette.theme": "Darstellung: {name}",
  "palette.language": "Sprache: {name}",
  "palette.goal": "Sparziel festlegen",
  "shortcuts.palette": "Befehlspalette",
  "shortcuts.title": "Tastenkürzel",
  "shortcuts.newSpending": "Neue Ausgabe",
  "shortcuts.newIncome": "Neue Einnahme",
  "shortcuts.newCategory": "Neue Ausgaben-Kategorie",
  "shortcuts.search": "Suchen",
  "shortcuts.saveAndNext": "Speichern und neu (im Eintrags-Dialog)",
  "shortcuts.clear": "Suche löschen / Auswahl aufheben / Dialog schließen",
  "shortcuts.print": "Drucken",
  "shortcuts.help": "Diese Liste anzeigen",
  "shortcuts.hint": "Tastenkürzel gelten, solange kein Dialog oder Eingabefeld aktiv ist.",

  "kind.income": "Einnahmen",
  "kind.spending": "Ausgaben",
  "kindInline.income": "Einnahmen",
  "kindInline.spending": "Ausgaben",

  "block.expandAll": "Alle aufklappen",
  "block.collapseAll": "Alle zuklappen",
  "block.addCategory": "Kategorie",
  "block.addEntry.income": "Einnahme",
  "block.addEntry.spending": "Ausgabe",
  "block.perMonth": "/ Monat",
  "block.perYear": "/ Jahr",
  "block.column.name": "Name",
  "block.column.entered": "Zahlweise",
  "block.column.due": "Fällig",
  "block.selectAll": "Einträge auswählen (nochmals klicken wählt alle dieses Blocks)",
  "block.column.perMonth": "Pro Monat",
  "block.column.perYear": "Pro Jahr",
  "block.empty.income": "Noch keine Einnahmen-Kategorien. Lege zuerst eine Kategorie an und füge ihr dann Einträge hinzu.",
  "block.empty.spending": "Noch keine Ausgaben-Kategorien. Lege zuerst eine Kategorie an und füge ihr dann Einträge hinzu.",
  "block.noMatch": "Keine Einträge passen zur aktuellen Suche oder zum Filter.",

  "category.dragHint": "Ziehen, um Kategorien zu sortieren",
  "category.addEntry": "Eintrag hinzufügen",
  "category.rename": "Umbenennen",
  "category.delete": "Löschen",
  "category.inUse": "Kategorie wird verwendet",
  "category.noEntries": "Noch keine Einträge",
  "category.dropHere": "Hier ablegen",
  "category.dropInto": "Ablegen, um zu „{name}“ hinzuzufügen",

  "entry.dragHint": "Ziehen, um zu sortieren oder in eine andere Kategorie zu verschieben",
  "entry.edit": "Bearbeiten",
  "entry.delete": "Löschen",
  "entry.monthly": "monatlich",
  "entry.quarterly": "vierteljährlich",
  "entry.halfyearly": "halbjährlich",
  "entry.yearly": "jährlich",
  "entry.paused": "pausiert",
  "entry.pause": "Pausieren (nicht mitzählen)",
  "entry.resume": "Fortsetzen (wieder mitzählen)",
  "entry.duplicate": "Duplizieren",
  "entry.notes": "Notizen",
  "entry.select": "Auswählen (Strg+Klick wechselt, Umschalt+Klick wählt einen Bereich)",

  "selection.count.one": "{count} Eintrag ausgewählt",
  "selection.count.other": "{count} Einträge ausgewählt",
  "selection.moveTo": "Verschieben nach…",
  "selection.move": "Verschieben",
  "selection.mixed": "Einnahmen und Ausgaben können nicht gemeinsam verschoben werden.",
  "selection.pause": "Pausieren",
  "selection.resume": "Fortsetzen",
  "selection.delete": "Löschen",
  "selection.clear": "Auswahl aufheben",
  "selection.done": "Fertig",
  "selection.count.zero": "Keine Einträge ausgewählt",
  "confirm.deleteEntries.title": "Einträge löschen",
  "confirm.deleteEntries.message.one": "{count} Eintrag löschen?",
  "confirm.deleteEntries.message.other": "{count} Einträge löschen?",
  "toast.entriesDeleted.one": "{count} Eintrag gelöscht.",
  "toast.entriesDeleted.other": "{count} Einträge gelöscht.",
  "toast.entriesMoved.one": "{count} Eintrag nach „{name}“ verschoben.",
  "toast.entriesMoved.other": "{count} Einträge nach „{name}“ verschoben.",
  "toast.entriesPaused.one": "{count} Eintrag pausiert.",
  "toast.entriesPaused.other": "{count} Einträge pausiert.",
  "toast.entriesResumed.one": "{count} Eintrag fortgesetzt.",
  "toast.entriesResumed.other": "{count} Einträge fortgesetzt.",

  "month.1": "Januar",
  "month.2": "Februar",
  "month.3": "März",
  "month.4": "April",
  "month.5": "Mai",
  "month.6": "Juni",
  "month.7": "Juli",
  "month.8": "August",
  "month.9": "September",
  "month.10": "Oktober",
  "month.11": "November",
  "month.12": "Dezember",

  "stats.title": "Statistik",
  "stats.transfers": "Monatliche Überweisungen",
  "stats.toBank": "Auf das Girokonto",
  "stats.toBankSub": "monatlich bezahlte Ausgaben",
  "stats.toSavings": "Auf das Sparkonto",
  "stats.toSavingsSub": "1/12 der jährlich bezahlten Ausgaben",
  "stats.overview": "Übersicht",
  "stats.incomePerMonth": "Einnahmen pro Monat",
  "stats.avgCostPerMonth": "Durchschnittliche Kosten pro Monat",
  "stats.saldoPerMonth": "Saldo pro Monat",
  "stats.incomePerYear": "Einnahmen pro Jahr",
  "stats.costPerYear": "Kosten pro Jahr",
  "stats.saldoPerYear": "Saldo pro Jahr",
  "stats.goal": "Sparziel pro Monat",
  "stats.goalNone": "kein Sparziel",
  "stats.goalEdit": "Sparziel festlegen",
  "stats.remainingAfterGoal": "Verbleibend nach Sparziel",
  "stats.peakBuffer": "Benötigter Puffer auf dem Sparkonto (Spitze)",
  "stats.unscheduled.one": "{count} nicht-monatlicher Eintrag ohne Fälligkeitsmonat fehlt in der Zeitleiste.",
  "stats.unscheduled.other": "{count} nicht-monatliche Einträge ohne Fälligkeitsmonat fehlen in der Zeitleiste.",
  "stats.paused.one": "{count} pausierter Eintrag wird nicht mitgezählt.",
  "stats.paused.other": "{count} pausierte Einträge werden nicht mitgezählt.",
  "stats.timeline": "Zahlungs-Zeitleiste",
  "stats.timelineDue": "fällig",
  "stats.timelineSaved": "auf dem Sparkonto",
  "stats.timelineEmpty": "Gib nicht-monatlichen Ausgaben einen Fälligkeitsmonat, um zu sehen, wann sie fällig sind und wie sich das Sparkonto füllt.",
  "stats.levers": "Größte Hebel",
  "stats.leversHint": "Die fünf aktiven Ausgaben mit den höchsten Jahreskosten.",
  "stats.leversEmpty": "Noch keine Ausgaben.",
  "stats.byCategory": "Ausgaben nach Kategorie",
  "stats.otherCategories": "Sonstige",
  "stats.chartsEmpty": "Noch keine Ausgaben.",
  "warning.negativeSaldo": "Die Ausgaben übersteigen die Einnahmen um {amount} pro Monat.",
  "warning.goal": "Das Sparziel ist nicht erreichbar: es fehlen {amount} pro Monat.",
  "goalDialog.title": "Sparziel",
  "goalDialog.amount": "Betrag, der monatlich zurückgelegt werden soll",
  "goalDialog.hint": "0 eingeben, um das Sparziel zu entfernen.",
  "toast.goalSaved": "Sparziel gespeichert.",
  "stats.note":
    "Monatliche Ausgaben werden vom Girokonto bezahlt. Jährliche Ausgaben werden Monat für Monat auf dem Sparkonto angespart, damit das Geld bei Fälligkeit vorhanden ist.",

  "dialog.cancel": "Abbrechen",
  "dialog.ok": "OK",
  "dialog.close": "Schließen",
  "dialog.save": "Speichern",
  "dialog.add": "Hinzufügen",
  "dialog.delete": "Löschen",
  "dialog.dismiss": "Ausblenden",

  "categoryDialog.titleNew.income": "Neue Einnahmen-Kategorie",
  "categoryDialog.titleNew.spending": "Neue Ausgaben-Kategorie",
  "categoryDialog.titleRename": "Kategorie umbenennen",
  "categoryDialog.name": "Name",
  "categoryDialog.namePlaceholder": "z. B. Wohnen",
  "categoryDialog.submit": "Kategorie anlegen",
  "categoryDialog.submitAndEntry": "Anlegen und Eintrag erfassen",
  "categoryDialog.submitAndEntryTip": "Legt die Kategorie an und öffnet den Dialog für den ersten Eintrag.",

  "entryDialog.titleNew.income": "Neue Einnahme",
  "entryDialog.titleNew.spending": "Neue Ausgabe",
  "entryDialog.titleEdit.income": "Einnahme bearbeiten",
  "entryDialog.titleEdit.spending": "Ausgabe bearbeiten",
  "entryDialog.noCategories.income":
    "Es gibt noch keine Einnahmen-Kategorien. Kategorien müssen angelegt werden, bevor Einträge erfasst werden können.",
  "entryDialog.noCategories.spending":
    "Es gibt noch keine Ausgaben-Kategorien. Kategorien müssen angelegt werden, bevor Einträge erfasst werden können.",
  "entryDialog.addCategoryFirst": "Zuerst eine Kategorie anlegen",
  "entryDialog.name": "Name",
  "entryDialog.namePlaceholder": "z. B. Miete",
  "entryDialog.amount": "Betrag",
  "entryDialog.paid": "Zahlung",
  "entryDialog.perMonth": "pro Monat",
  "entryDialog.perQuarter": "pro Quartal",
  "entryDialog.perHalfYear": "pro Halbjahr",
  "entryDialog.perYear": "pro Jahr",
  "entryDialog.category": "Kategorie",
  "entryDialog.preview": "= {monthly} pro Monat · {yearly} pro Jahr",
  "entryDialog.dueMonth": "Fälligkeitsmonat",
  "entryDialog.dueMonthNone": "nicht festgelegt",
  "entryDialog.dueMonthHint": "Monat einer Zahlung; weitere Zahlungen folgen alle {months} Monate. Wird für die Zeitleiste benötigt.",
  "entryDialog.notes": "Notizen",
  "entryDialog.notesPlaceholder": "z. B. Vertragsnummer, Kündigungsfrist",
  "entryDialog.paused": "Pausiert – Eintrag behalten, aber bei allen Summen weglassen",
  "entryDialog.titleDuplicate.income": "Einnahme duplizieren",
  "entryDialog.titleDuplicate.spending": "Ausgabe duplizieren",
  "entryDialog.copySuffix": " (Kopie)",
  "entryDialog.saveAndNext": "Speichern und neu",
  "entryDialog.saveAndNextTip": "Speichert diesen Eintrag und lässt den Dialog für den nächsten offen, Kategorie und Zahlweise bleiben stehen (Strg+Enter).",
  "entryDialog.invalidAmount": "Bitte einen gültigen Betrag eingeben, z. B. 12,50.",

  "confirm.deleteEntry.title": "Eintrag löschen",
  "confirm.deleteEntry.message": "„{name}“ löschen? Das kann nicht rückgängig gemacht werden.",
  "confirm.deleteCategory.title": "Kategorie löschen",
  "confirm.deleteCategory.message": "Die Kategorie „{name}“ löschen?",
  "confirm.categoryInUse.title": "Kategorie wird verwendet",
  "confirm.categoryInUse.message.one":
    "„{name}“ enthält noch {count} Eintrag. Verschiebe oder lösche ihn zuerst, dann kann die Kategorie gelöscht werden.",
  "confirm.categoryInUse.message.other":
    "„{name}“ enthält noch {count} Einträge. Verschiebe oder lösche sie zuerst, dann kann die Kategorie gelöscht werden.",

  "importDialog.title": "Daten importieren",
  "importDialog.summary": "{file} enthält {categories} und {entries} (Dateiversion {version}).",
  "importDialog.categories.one": "{count} Kategorie",
  "importDialog.categories.other": "{count} Kategorien",
  "importDialog.entries.one": "{count} Eintrag",
  "importDialog.entries.other": "{count} Einträge",
  "importDialog.question": "Wie sollen die Daten importiert werden?",
  "importDialog.merge.title": "Zu den aktuellen Daten hinzufügen",
  "importDialog.merge.description":
    "Behält alles Vorhandene. Kategorien mit gleichem Namen werden wiederverwendet, bereits vorhandene Einträge übersprungen.",
  "importDialog.replace.title": "Aktuelle Daten ersetzen",
  "importDialog.replace.description":
    "Löscht alle aktuellen Kategorien und Einträge und verwendet stattdessen die importierte Datei.",

  "toast.entryAdded": "„{name}“ hinzugefügt.",
  "toast.entrySaved": "„{name}“ gespeichert.",
  "toast.entryDeleted": "„{name}“ gelöscht.",
  "toast.entryPaused": "„{name}“ pausiert.",
  "toast.entryResumed": "„{name}“ fortgesetzt.",
  "toast.categoryAdded.income": "Einnahmen-Kategorie „{name}“ angelegt.",
  "toast.categoryAdded.spending": "Ausgaben-Kategorie „{name}“ angelegt.",
  "toast.categoryRenamed": "Kategorie in „{name}“ umbenannt.",
  "toast.categoryDeleted": "Kategorie „{name}“ gelöscht.",
  "toast.exported": "Exportiert nach {path}",
  "toast.importedMerge": "Import abgeschlossen: {entries}, {skipped}, {categories}.",
  "toast.importedMerge.entries.one": "{count} Eintrag hinzugefügt",
  "toast.importedMerge.entries.other": "{count} Einträge hinzugefügt",
  "toast.importedMerge.skipped.one": "{count} bereits vorhanden",
  "toast.importedMerge.skipped.other": "{count} bereits vorhanden",
  "toast.importedMerge.categories.one": "{count} neue Kategorie",
  "toast.importedMerge.categories.other": "{count} neue Kategorien",
  "toast.importedReplace": "Daten durch Import ersetzt: {entries} in {categories}.",

  "tip.blockMonthly": "Summe aller aktiven {kind}-Einträge pro Monat.\nNicht monatliche Beträge zählen mit ihrem Monatsanteil.\nPausierte Einträge zählen nicht.",
  "tip.blockYearly": "Summe aller aktiven {kind}-Einträge pro Jahr.\nMonatliche Beträge zählen × 12.\nPausierte Einträge zählen nicht.",
  "tip.categoryMonthly": "Monatssumme der aktiven Einträge in „{name}“.\nPausierte Einträge zählen nicht.",
  "tip.categoryYearly": "Jahressumme der aktiven Einträge in „{name}“.\nPausierte Einträge zählen nicht.",
  "tip.categoryShare": "Monatssumme von „{name}“:\n{percent} aller monatlichen Ausgaben\n{income} der monatlichen Einnahmen",
  "tip.categoryShareNoIncome": "Monatssumme von „{name}“:\n{percent} aller monatlichen Ausgaben",
  "tip.entryMaster": "Betrag wie eingegeben:\n{amount} {period}",
  "tip.entryMonthlyDerived": "Berechnet:\n{amount} {period} ÷ {months} Monate",
  "tip.entryYearlyDerived": "Berechnet:\n{amount} {period} × {payments} Zahlungen pro Jahr",
  "tip.toBank": "Summe aller monatlich bezahlten Ausgaben.\nDiesen Betrag jeden Monat auf das Girokonto überweisen.",
  "tip.toSavings": "Monatsanteil aller nicht monatlich bezahlten Ausgaben\n(vierteljährlich ÷ 3, halbjährlich ÷ 6, jährlich ÷ 12).\nDiesen Betrag jeden Monat auf das Sparkonto legen.",
  "tip.incomePerMonth": "Summe aller aktiven Einnahmen pro Monat.\nNicht monatliche Einnahmen zählen mit ihrem Monatsanteil.",
  "tip.avgCostPerMonth": "Summe aller aktiven Ausgaben pro Monat\n= Überweisung auf das Girokonto + Überweisung auf das Sparkonto.",
  "tip.saldoPerMonth": "Einnahmen pro Monat − durchschnittliche Kosten pro Monat",
  "tip.goal": "Der Betrag, der jeden Monat zusätzlich zu allen Ausgaben\nzurückgelegt werden soll.",
  "tip.remainingAfterGoal": "Saldo pro Monat − Sparziel.\nNegativ bedeutet: Das Sparziel ist nicht erreichbar.",
  "tip.incomePerYear": "Summe aller aktiven Einnahmen pro Jahr.",
  "tip.costPerYear": "Summe aller aktiven Ausgaben pro Jahr.",
  "tip.saldoPerYear": "Einnahmen pro Jahr − Kosten pro Jahr",
  "tip.peakBuffer": "Höchster Stand des Sparkontos im Jahresverlauf.\nDas ist der Puffer, den das Konto braucht, damit jede geplante Zahlung gedeckt ist.",
  "tip.timelineDue": "Summe der nicht monatlichen Ausgaben, die in diesem Monat bezahlt werden.",
  "tip.timelineSaved": "Stand des Sparkontos am Monatsende:\nZurückgelegtes minus Ausgezahltes.",
  "tip.lever": "{yearly} pro Jahr\n{monthly} pro Monat\n{share} aller monatlichen Ausgaben\n{income} der monatlichen Einnahmen\n\nZum Bearbeiten anklicken.",
  "tip.leverNoIncome": "{yearly} pro Jahr\n{monthly} pro Monat\n{share} aller monatlichen Ausgaben\n\nZum Bearbeiten anklicken.",
  "tip.donutSlice": "{name}\n{amount} pro Monat\n{percent} aller monatlichen Ausgaben",

  "alert.generic": "Etwas ist schiefgelaufen",
  "alert.deleteFailed": "Löschen fehlgeschlagen",
  "alert.moveFailed": "Verschieben fehlgeschlagen",
  "alert.exportFailed": "Export fehlgeschlagen",
  "alert.importFailed": "Import fehlgeschlagen",

  "errors.kind.unknown": "Unbekannte Art „{kind}“.",
  "errors.period.unknown": "Unbekannter Zeitraum „{period}“.",
  "errors.category.notFound": "Die Kategorie wurde nicht gefunden.",
  "errors.category.nameEmpty": "Der Kategoriename darf nicht leer sein.",
  "errors.category.exists": "Eine {kind}-Kategorie mit dem Namen „{name}“ existiert bereits.",
  "errors.category.inUse.one": "Die Kategorie „{name}“ wird noch von {count} Eintrag verwendet und kann nicht gelöscht werden.",
  "errors.category.inUse.other": "Die Kategorie „{name}“ wird noch von {count} Einträgen verwendet und kann nicht gelöscht werden.",
  "errors.entry.notFound": "Der Eintrag wurde nicht gefunden.",
  "errors.entry.categoryRequired": "Bitte eine Kategorie auswählen.",
  "errors.entry.nameEmpty": "Der Name darf nicht leer sein.",
  "errors.entry.amountPositive": "Der Betrag muss größer als 0 sein.",
  "errors.entry.dueMonthInvalid": "Der Fälligkeitsmonat muss zwischen 1 und 12 liegen.",
  "errors.entry.idExists": "Der Eintrag existiert bereits.",
  "errors.category.idExists": "Die Kategorie existiert bereits.",
  "errors.settings.savingsGoalNegative": "Das Sparziel darf nicht negativ sein.",
  "errors.settings.themeInvalid": "Unbekannte Darstellung „{theme}“.",
  "errors.sample.notEmpty": "Beispieldaten können nur in einen leeren Planer geladen werden.",
  "errors.backup.invalidPath": "Es können nur Dateien aus dem Backup-Ordner wiederhergestellt werden.",
  "errors.entry.kindMismatch": "Ein {from}-Eintrag kann nicht in eine {to}-Kategorie verschoben werden.",
  "errors.import.modeUnknown": "Unbekannter Importmodus „{mode}“.",
  "errors.import.invalidFile": "{file} ist keine gültige Planer-Datei: {detail}",
  "errors.language.invalid": "Nicht unterstützte Sprache „{language}“.",
};
